-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


DROP TABLE IF EXISTS public."Customers";

CREATE TABLE IF NOT EXISTS public."Customers"
(
    id_clientes bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 ),
    name character varying(25),
    mail character varying(25),
    phone integer,
    PRIMARY KEY (id_clientes)
);

DROP TABLE IF EXISTS public."Orders";

CREATE TABLE IF NOT EXISTS public."Orders"
(
    order_id bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    customers_id bigint NOT NULL,
    date date,
    address character varying NOT NULL,
    total real NOT NULL,
    "Product_id" bigint NOT NULL,
    PRIMARY KEY (order_id)
);

DROP TABLE IF EXISTS public."Product";

CREATE TABLE IF NOT EXISTS public."Product"
(
    "Product_id" bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 ),
    name character varying(25) NOT NULL,
    description character varying(250),
    price real NOT NULL,
    PRIMARY KEY ("Product_id")
);

DROP TABLE IF EXISTS public."Categories";

CREATE TABLE IF NOT EXISTS public."Categories"
(
    "Category_id" bigint NOT NULL,
    name character varying(25) NOT NULL,
    PRIMARY KEY ("Category_id")
);

DROP TABLE IF EXISTS public."Orders_Product";

CREATE TABLE IF NOT EXISTS public."Orders_Product"
(
    "Orders_Product_id" bigint NOT NULL,
    "Product_Product_id" bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 )
);

ALTER TABLE IF EXISTS public."Orders"
    ADD CONSTRAINT id_clientes FOREIGN KEY (customers_id)
    REFERENCES public."Customers" (id_clientes) MATCH FULL
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Orders_Product"
    ADD FOREIGN KEY ("Orders_Product_id")
    REFERENCES public."Orders" ("Product_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Orders_Product"
    ADD FOREIGN KEY ("Product_Product_id")
    REFERENCES public."Product" ("Product_id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;